version: '3.8'
services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: poke-api
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - .env