# Generated by Django 4.2.2 on 2023-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berrie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('growth_time', models.IntegerField()),
                ('max_harvest', models.IntegerField()),
                ('natural_gift_power', models.IntegerField()),
                ('size', models.IntegerField()),
                ('smoothness', models.IntegerField()),
                ('soil_dryness', models.IntegerField()),
                ('firmness', models.CharField(max_length=255)),
                ('flavors', models.JSONField()),
                ('natural_gift_type', models.CharField(max_length=255)),
            ],
        ),
    ]
